# -*- coding: utf-8 -*-
"""Study_buddy_for_intership(2)(1).py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GJYMSjCKmHZqVE6h22OsmpIY_UyCapg
"""

!pip install transformers torch sentencepiece gradio
from transformers import pipeline

# Load AI pipelines
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
generator = pipeline("text2text-generation", model="google/flan-t5-base")

print("AI Study Buddy is ready!")

# --------- STUDY BUDDY FUNCTIONS ---------

def summarize_notes(text):
    summary = summarizer(text, max_length=150, min_length=60, do_sample=False)
    return summary[0]['summary_text']


def create_flashcards(text):
    prompt = f"""
    Create 5 flashcards from the following notes.
    Format:
    Q: Question
    A: Answer

    Notes:
    {text}
    """
    result = generator(prompt, max_length=300)
    return result[0]['generated_text']


def generate_quiz(text):
    prompt = f"""
    Create a short quiz with 5 multiple choice questions from the notes below.
    Provide correct answers at the end.

    Notes:
    {text}
    """
    result = generator(prompt, max_length=400)
    return result[0]['generated_text']


print("Study Buddy features loaded!")

def create_flashcards(text):
    prompt = f"""
    Create 5 flashcards from the notes below.

    Each flashcard should be in this format:
    Question: ...
    Answer: ...

    Notes:
    {text}
    """

    result = generator(
        prompt,
        max_length=400,
        do_sample=True,
        temperature=0.8
    )
    return result[0]['generated_text']

def generate_quiz(text):
    prompt = f"""
    Based ONLY on the notes below, create 5 DIFFERENT multiple-choice questions.

    Rules:
    - Each question must test a different fact or idea
    - Do NOT repeat the same question
    - Each question must have 4 options (A, B, C, D)
    - After each question, write: Correct answer: X

    Notes:
    {text}

    Start now.
    """

    result = generator(
        prompt,
        max_length=600,
        do_sample=True,
        temperature=1.0,
        top_p=0.95
    )
    return result[0]['generated_text']

quiz_notes = """
Operating systems manage computer hardware and software resources.
Examples include Windows, Linux, and macOS.
Key functions include memory management, process scheduling, and file systems.
"""

print(generate_quiz(quiz_notes))

my_notes = """
The explanation below is attributed to John McCarthy, who first coined the term “artificial intelligence” in 1956.
" It is the science and engineering of making intelligent machines, especially intelligent computer programs. It is related to the similar task of using computers to understand human intelligence, but AI does not have to confine itself to methods that are biologically observable.“
"""

print("SUMMARY:\n")
print(summarize_notes(my_notes))

print("\nFLASHCARDS:\n")
print(create_flashcards(my_notes))

print("\nQUIZ:\n")
print(generate_quiz(my_notes))

sample_notes = """
Machine Learning is a subset of Artificial Intelligence that focuses on
algorithms that learn from data. It includes supervised learning,
unsupervised learning, and reinforcement learning.
"""

print("SUMMARY:\n")
print(summarize_notes(sample_notes))

print("\nFLASHCARDS:\n")
print(create_flashcards(sample_notes))

print("\nQUIZ:\n")
print(generate_quiz(sample_notes))

import gradio as gr

def study_buddy_app(notes):
    summary = summarize_notes(notes)
    flashcards = create_flashcards(notes)
    quiz = generate_quiz(notes)
    return summary, flashcards, quiz

demo = gr.Interface(
    fn=study_buddy_app,
    inputs=gr.Textbox(lines=10, placeholder="Paste your study notes here..."),
    outputs=[
        gr.Textbox(lines=6, label="Summary"),
        gr.Textbox(lines=10, label="Flashcards"),
        gr.Textbox(lines=12, label="Quiz")
    ],
    title="AI-Powered Study Buddy",
    description="Summarizes notes, creates flashcards, and generates quizzes using AI"
)

demo.launch()

!jupyter nbconvert --to script your_notebook_name.ipynb

import gradio as gr

# Paste your existing functions here
# Example placeholders:
def summarize_notes(notes):
    return "Summary:\n" + notes[:200] + "..."

def create_flashcards(notes):
    return "Flashcards:\nQ1: Example?\nA1: Example Answer"

def generate_quiz(notes):
    return "Quiz:\nQ1: Example?\n(a) Option1 (b) Option2 (c) Option3 (d) Option4"

# Function to call all three
def study_buddy_app(notes):
    summary = summarize_notes(notes)
    flashcards = create_flashcards(notes)
    quiz = generate_quiz(notes)
    return summary, flashcards, quiz

# Gradio interface
demo = gr.Interface(
    fn=study_buddy_app,
    inputs=gr.Textbox(lines=10, placeholder="Paste your study notes here..."),
    outputs=[
        gr.Textbox(lines=6, label="Summary"),
        gr.Textbox(lines=10, label="Flashcards"),
        gr.Textbox(lines=12, label="Quiz")
    ],
    title="AI-Powered Study Buddy",
    description="Summarizes notes, creates flashcards, and generates quizzes using AI"
)

demo.launch()